
apiVersion: v1
kind: Service
metadata:
  name: {{ template "am-pattern-3.resource.prefix" . }}-am-publisher-lb
  namespace : {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    #kubernetes.io/ingress.class: alb
    #alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  selector:
    deployment: {{ template "am-pattern-3.resource.prefix" . }}-am-publisher
  ports:
    -
      name: 'publisher'
      port: 443
      targetPort: 9443
      protocol: TCP
  type: LoadBalancer

