apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-2.resource.prefix" . }}-am-gateway-shared-synapse-configs-volume-claim
  namespace : {{ .Release.Namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.sharedArtifacts.capacity.synapseConfigs }}
  #storageClassName: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}
