
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-2.resource.prefix" . }}-am-shared-executionplans-volume-claim
  namespace : {{ .Release.Namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.sharedArtifacts.capacity.executionPlans }}
  #storageClassName: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}

  {{ if .Values.wso2.deployment.persistentRuntimeArtifacts.apacheSolrIndexing.enabled }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-2.resource.prefix" . }}-am-1-local-carbon-database-volume-claim
  namespace : {{ .Release.Namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.apacheSolrIndexing.capacity.carbonDatabase }}
  #storageClassName: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-2.resource.prefix" . }}-am-1-solr-indexed-data-volume-claim
  namespace : {{ .Release.Namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.apacheSolrIndexing.capacity.solrIndexedData }}
  #storageClassName: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-2.resource.prefix" . }}-am-2-local-carbon-database-volume-claim
  namespace : {{ .Release.Namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.apacheSolrIndexing.capacity.carbonDatabase }}
  #storageClassName: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-2.resource.prefix" . }}-am-2-solr-indexed-data-volume-claim
  namespace : {{ .Release.Namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.apacheSolrIndexing.capacity.solrIndexedData }}
  #storageClassName: {{ .Values.wso2.deployment.persistentRuntimeArtifacts.storageClass }}
  {{ end }}
